api/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from django.urls import path


from rest_framework.authtoken import views
from api.products_view import productnew, updatestok, List_produ


from api.auth_views import CustomAuthToken



urlpatterns = [

   path('api-token-auth/', views.obtain_auth_token),
   path('api-token-auth-2/', CustomAuthToken.as_view()),
   path('add_product/', productnew),
   path('update_stok/<int:pk>/', updatestok),
   path('list_product/', List_produ),
]  

store/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from productos import urls as url_products
from usuarios import urls as url_users
from orden import urls as url_order
from api import urls as url_api
#from productos import urls as url_cart

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(url_products)),
    path('', include(url_users)),
    path('', include(url_order)),
    #path('', include(url_cart)),
    #path('/', admin.site.urls),
   path('api/', include(url_api)),
    


]

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuarios/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from django.urls import path


# View
from usuarios import views


urlpatterns = [

    # Posts
    path('usernew', views.user_new, name='user_new'),
    path('userlist', views.list_user, name='list_user'),
    path('detall/<int:pk>/', views.Detalle_user, name='Detalle_user'),
    path('cuenta', views.Cuenta, name='Cuenta'),
    path('admi', views.Admin, name='Admin'),
   
    

    

]

usuarios/models.py
#Models de usuarios
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.translation import ugettext as _
# Create your models here.


class Perfil(AbstractUser):
    """ Modelo de perfil de usuario """
    USERNAME_FIELD = 'username'

    edad = models.IntegerField(verbose_name=_('Edad'), blank=True, null=True)
    telefono = models.CharField(verbose_name=_('Teléfono'), max_length=15, blank=True, null=True)
    sexo_options = (
        (1, 'Hombre'),
        (2, 'Mujer'),

    )
    sexo = models.IntegerField(verbose_name=_('Sexo'), choices=sexo_options, blank=True, null=True)
    direccion = models.TextField(verbose_name=_('Dirección'), max_length=1000, blank=True, null=True)
    
    #Diccionario de formulario
    estado_options = (
        (1, 'aguascalientes'),
        (2, 'bajacalifornia'),
        (3, 'bajacaliforniasur'),
        (4, 'campeche'),
        (5, 'coahuila'),
        (6, 'chiapas'),
        (7, 'chiapas'),
        (8, 'chihuahua'),
        (9, 'distritofederal'),
        (10, 'durango'),
        (11, 'guanajuato'),
        (12, 'guerrero'),
        (13, 'hidalgo'),
        (14, 'jalisco'),
        (15, 'mexico'),
        (16, 'michoacan'),




        )

    estado = models.IntegerField(verbose_name=_('estado'), choices=estado_options, blank=True, null=True)
    codigo = models.IntegerField(verbose_name=('codigo'), blank=True, null=True)

usuarios/forms.py
from django import forms
from usuarios.models import Perfil

from django.utils.translation import ugettext as _
class PerfilForm(forms.ModelForm):

    username = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': _('Nombre de usuario'), 'class': "form-control"}),
        max_length=80,
        error_messages={'required': _(u'Ingrese un usuario válido')},
        label=_('Nombre de usuario'),
        required=True,
    )

    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': _('Nombre(s)'), 'class': "form-control"}),
        max_length=80,
        error_messages={'required': _(u'Ingrese un nombre válido')},
        label=_('Nombre(s)*'),
        required=True,
    )

    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'placeholder': _('Apellidos(s)'), 'class': "form-control"}),
        max_length=80,
        error_messages={'required': _(u'Ingrese un apellido válido')},
        label=_('Apellidos(s)*'),
        required=True,
    )


    direccion = forms.CharField(
        widget=forms.Textarea(attrs={'placeholder': _('Dirección'), 'class': "form-control"}),
        max_length=200,
        error_messages={'required': _(u'Ingrese una dirección valida.')},
        label=_('Dirección'),
        required=True,
    )

    CHOICES= (
        ('1','Hombre'),
        ('2','Mujer'),
        )

    sexo = forms.ChoiceField(
        widget=forms.Select( attrs={'class': "form-control"}),
        choices=CHOICES,
        error_messages={'required': _(u'Seleccion tu Sexo')},
        label=_('Sexo'),
        required=True,
    )

    codigo = forms.IntegerField(
        widget=forms.NumberInput(attrs={'placeholder': _('Codigo Postal'), 'class': "form-control"}),
        error_messages={'required': _(u'Ingrese un codigo postal')},
        label=_('Codigo Postal'),
        required=True,
    )

    edad = forms.IntegerField(
        widget=forms.NumberInput(attrs={'placeholder': _('Edad'), 'class': "form-control"}),
        error_messages={'required': _(u'Ingrese Edad ')},
        label=_('Edad'),
        required=True,
    )

    CHOICES= (
        ('1','aguascalientes'),
        ('2','bajacalifornia'),
        ('3','bajacaliforniasur'),
        ('4','campeche'),
        ('5','coahuila'),
        ('6','chiapas'),
        ('7','chiapas'),
        ('8','chihuahua'),
        ('9','distritofederal'),
        ('10','durango'),
        ('11','guanajuato'),
        ('12','guerrero'),
        ('13','hidalgo'),
        ('14','jalisco'),
        ('15','mexico'),
        ('16','michoacan'),
        )

    estado = forms.ChoiceField(
        widget=forms.Select( attrs={'class': "form-control"}),
        choices=CHOICES,
        error_messages={'required': _(u'Seleccion tu Estado')},
        label=_('Estado'),
        required=True,
    )


    email = forms.EmailField(
        widget=forms.TextInput(attrs={'placeholder': _('Email(s)'), 'class': "form-control"}),
        max_length=80,
        error_messages={'required': _(u'Ingrese su Email')},
        label=_('Email'),
        required=True,
    )

    telefono = forms.IntegerField(
        widget=forms.NumberInput(attrs={'placeholder': _('Telefono'), 'class': "form-control"}),
        error_messages={'required': _(u'Ingrese su Telefono ')},
        label=_('Telefono'),
        required=True,
    )




    class Meta:
        model = Perfil
        fields = ('username','first_name', 'last_name', 'direccion', 'sexo', 'codigo', 'edad', 'estado', 'email', 'telefono', )





        

usuarios/views.py
from django.shortcuts import render, redirect

from usuarios.forms import PerfilForm


from usuarios.models import Perfil

# Creacion vista usuer para ingresar datos del usuario
def user_new(request):
    if request.method == 'POST':
        #form = profileForm(request.POST, instance=request.user)  ##para actualizar un objeto en la base de datos
        form = PerfilForm(request.POST)  #para crear un nuevo objeto en la base
        if form.is_valid():
            form.save()

            #new_user = Perfil.objects.create(first_name=data['nombrecompleto'], last_name=data['apellido'], direccion = data['direc'])

            return redirect('home')

    else:
    	form = PerfilForm() #para crer un nuevo objeto
        #form = profileForm(instance=request.user)   ##para actualizar un objeto en la base de datos


    return render(
        request=request,
        template_name='user_new.html',
        context={
            #'profile': profile,
            'form': form
        })


#listar usuarios en el template
def list_user(request):

    perfiles = Perfil.objects.all()

    return render(
        request=request,
        template_name='list_user.html',
        context={
            'perfiles': perfiles,
          
        })

#detalles de usuario en el template
def Detalle_user(request, pk):


    perfil = Perfil.objects.get(pk=pk)


    return render(
        request=request,
        template_name='Detalle_user.html',
        context={
            'perfil': perfil,
          
        })

def Cuenta(request):


    return render(request,'Mi-cuenta.html')


def Admin(request):


    return render(request,'Administrador.html')



	
   

usuarios/templates/Administrador.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}

{% endblock %}

{% block container %}


<section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Prueba 1 Tienda</h1>
          <p class="lead text-muted">TicSup.</p>
          <p>
            <a href="/list" class="btn btn-secondary my-2">Lista de Prodcutos</a>
            <a href="/usernew" class="btn btn-secondary my-2">Agregar Usuario</a>
            <a href="/userlist" class="btn btn-secondary my-2">Lista de Usuarios</a>
            <a href="/cartlist" class="btn btn-secondary my-2">Carritos</a>
            <a href="/listorden" class="btn btn-secondary my-2">Lista de Ordenes</a>
            <a href="/listpago" class="btn btn-secondary my-2">Lista de Pagos</a>

            
            
          </p>
        </div>
      </section>



{% endblock %}

usuarios/templates/Detalle_user.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}

{% endblock %}

{% block container %}



          <h2>DETALLES DE USUARIOS</h2>
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>Username</th>
                  <th>First name</th>
                  <th>Apellido</th>
                  <th>Direccion</th>
                  <th>Sexo</th>
                  <th>Codigo</th>
                  <th>Edad</th>
                  <th>Estado</th>
                  <th>Email</th>
                  <th>Telefono</th>

                </tr>
              </thead>
              <tbody>


                <tr>
                  <td>{{perfil.username}}</td>
                  <td>{{perfil.first_name}}</td>
                  <td>{{perfil.last_name}}</td>
                  <td>{{perfil.direccion}}</td>
                  <td>{{perfil.get_sexo_display}}</td>
                  <td>{{perfil.codigo}}</td>
                  <td>{{perfil.edad}}</td>
                  <td>{{perfil.estado}}</td>
                  <td>{{perfil.email}}</td>
                  <td>{{perfil.telefono}}</td>
                </tr>
                 
         
              </tbody>
            </table>
          </div>
          




{% endblock %}

usuarios/templates/Mi-cuenta.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}

{% endblock %}

{% block container %}


<section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Tienda</h1>
          <p class="lead text-muted">TicSup.</p>
          <p>
            <a href="/list" class="btn btn-secondary my-2">Lista de Prodcutos</a>
            <a href="/listorden" class="btn btn-secondary my-2">Lista de Ordenes</a>
            <a href="/listpago" class="btn btn-secondary my-2">Lista de Pagos</a>
          </p>
        </div>
      </section>



{% endblock %}

usuarios/templates/list_user.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}

{% endblock %}

{% block container %}



          <h2>LISTA DE USUARIOS</h2>
          <div class="table-responsive">
            <table class="table table-striped table-sm">
              <thead>
                <tr>
                  <th>Username</th>
                  <th>First name</th>
                  <th>Apellido</th>
                  <th>Direccion</th>
                  <th>Sexo</th>
                  <th>Help</th>

                </tr>
              </thead>
              <tbody>

{% for perfil in perfiles %}
                <tr>
                  <td>{{perfil.username}}</td>
                  <td>{{perfil.first_name}}</td>
                  <td>{{perfil.last_name}}</td>
                  <td>{{perfil.direccion}}</td>
                  <td>{{perfil.get_sexo_display}}</td>
                  <td><a href='{% url "Detalle_user" perfil.pk %}'> Detalle usuario </a></td>
                </tr>
                 
{% endfor %}                
              </tbody>
            </table>
          </div>
          




{% endblock %}

usuarios/templates/user_new.html
{% extends "base.html" %}
{% load static %}

{% block head_content %}

{% endblock %}

{% block container %}

<div class="container">

    <div class="row justify-content-md-center">
        <div class="col-6 p-4" id="profile-box">

            <form action="{% url 'user_new' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}

   {{ form }}
                {% if form.errors %}
                    <p class="alert alert-danger">{{ form.errors }}</p>
                {% endif %}


                <hr><br>

                <button type="submit" class="btn btn-primary btn-block mt-5">Enviar</button>
            </form>


        </div>
    </div>
</div>

{% endblock %}